Update patch set 1
Patch Set 1:

Hello Mickael,

I'm trying the approach with a bundle pool and I think it would work, but there is more work to be done.
With the changes in PS1, I'm able to run 'mvn clean install', but I cannot use it in our product build for some reason.

Is there something else that I'm expected to run in the tycho tree in order to have a working plugin structure? Any profiles I need to activate?

Here is the error I get:
[WARNING] The POM for org.eclipse.tycho:tycho-standalone-p2-director:zip:2.3.0-SNAPSHOT is missing, no dependency information available
[ERROR] Internal error: java.lang.RuntimeException: org.apache.maven.MavenExecutionException: Could not setup plugin ClassRealm: Plugin org.eclipse.tycho:tycho-p2-director-plugin:2.3.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.eclipse.tycho:tycho-standalone-p2-director:zip:2.3.0-SNAPSHOT -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: org.apache.maven.MavenExecutionException: Could not setup plugin ClassRealm


Reading the pom.xml files in the tycho tree, I cannot see any reason why it should not be built, but I can confirm that there is no 2.3.0-SNAPSHOT directory under ~/.m2/repository//org/eclipse/tycho/tycho-standalone-p2-director/.

Patch-set: 1
Reviewer: Gerrit User 587 <587@97ee7c02-f12f-4043-b43e-dea463d88b31>