Update patch set 11
Patch Set 11:

I noticed it works with maven 3.6.1, but not 3.6.2 or 3.6.3. When looking at the maven changelog I saw this change in 3.6.2 that I suspect may be troublesome: https://issues.apache.org/jira/browse/MNG-6685

(Issue about converting maven-model to JSR 330 annotations from plexus annotations)

So I tried converting tycho-pomless to JSR 330 annotations and it made the error change....

Error when using plexus annotations in tycho-pomless:


[ERROR] testReadBundle(org.eclipse.tycho.pomless.TychoModelReaderTest)  Time elapsed: 0.049 s  <<< ERROR!
java.lang.RuntimeException:
org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.apache.maven.model.io.ModelReader
  roleHint: default
        at org.eclipse.tycho.pomless.TychoModelReaderTest.testReadBundle(TychoModelReaderTest.java:46)
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException:
java.util.NoSuchElementException
      role: org.apache.maven.model.io.ModelReader
  roleHint: default
        at org.eclipse.tycho.pomless.TychoModelReaderTest.testReadBundle(TychoModelReaderTest.java:46)
Caused by: java.util.NoSuchElementException
        at org.eclipse.tycho.pomless.TychoModelReaderTest.testReadBundle(TychoModelReaderTest.java:46)


Error when using JSR 330 annotations in tycho-pomless:


[ERROR] testReadBundle(org.eclipse.tycho.pomless.TychoModelReaderTest)  Time elapsed: 0.052 s  <<< ERROR!
org.codehaus.plexus.component.repository.exception.ComponentLookupException:
java.util.NoSuchElementException
      role: org.sonatype.maven.polyglot.mapping.Mapping
  roleHint: eclipse-plugin
        at org.eclipse.tycho.pomless.TychoModelReaderTest.getMapping(TychoModelReaderTest.java:228)
        at org.eclipse.tycho.pomless.TychoModelReaderTest.getTychoModelReader(TychoModelReaderTest.java:224)
        at org.eclipse.tycho.pomless.TychoModelReaderTest.testReadBundle(TychoModelReaderTest.java:46)
Caused by: java.util.NoSuchElementException
        at org.eclipse.tycho.pomless.TychoModelReaderTest.getMapping(TychoModelReaderTest.java:228)
        at org.eclipse.tycho.pomless.TychoModelReaderTest.getTychoModelReader(TychoModelReaderTest.java:224)
        at org.eclipse.tycho.pomless.TychoModelReaderTest.testReadBundle(TychoModelReaderTest.java:46)


So does imply takari-pomless also need to migrate to JSR 330 annotations?

Patch-set: 11
Reviewer: Gerrit User 888 <888@97ee7c02-f12f-4043-b43e-dea463d88b31>
Label: Code-Review=0