Update patch set 2
Patch Set 2:

Caused by: java.lang.NoSuchMethodError: org.eclipse.tycho.core.utils.TychoProjectUtils.getDependencySeeds(Lorg/apache/maven/project/MavenProject;)Ljava/util/List;
    at org.eclipse.tycho.plugins.p2.director.AbstractProductMojo.getProductConfig (AbstractProductMojo.java:146)

Seems like the build didn't compile everything, any idea what's going on?

Patch-set: 2
CC: Gerrit User 171685 <171685@97ee7c02-f12f-4043-b43e-dea463d88b31>