Update patch set 2
Patch Set 2:

> I can reproduce the NoSuchMethodError on my personal machine. Let me know what I can do to debug this.

Good. I suggest you start by verifying that the IT test do use the expected jars of Tycho (locally built ones) instead of remote ones by finding those files and compating signatures.

Patch-set: 2